### ISSUE TITLE
Implement Edit distance algorithm

### ISSUE THREAD

**Issue by manishrw** [manishrw/Algorithms#4]
Find the edit distance of given 2 strings, where edit distance is the distance required to convert from string1 to string2. Please let me know if you need more details.

**Comment by rishisharan** [comment]
Hi,

I need more details.

#1. Can you give me some test cases?

**Comment by necrashter** [comment]
Do you want it to be case sensitive?
And which category/file should we put the script to?

**Comment by necrashter** [comment]
Hello again, I implemented one. please check it out and give me feedback. I can add comments etc. if you want.
